/**
 * DEVELOPMENT WEBPACK CONFIGURATION
 */

const path = require('path')
const webpack = require('webpack')
const CircularDependencyPlugin = require('circular-dependency-plugin')
const HtmlWebpackPlugin = require('html-webpack-plugin')

module.exports = require('./webpack.config.base')({
	// Add hot reloading in development
	entry: [
		'babel-polyfill',
		'webpack-hot-middleware/client?reload=true',
		path.join(__dirname, 'src/index.js') // Start with src/index.js
	],
	output: {
		filename: '[name].[hash].js'
	},
	module: {
		test: /\.sass/,
		use: ['style-loader', 'css-loader', 'sass-loader']
	},
	plugins: [
		new webpack.DefinePlugin({
			'process.env.NODE_ENV': JSON.stringify('development')
		}),
		new webpack.HotModuleReplacementPlugin(), // Tell webpack we want hot reloading
		new webpack.NoEmitOnErrorsPlugin(),
		new HtmlWebpackPlugin({
			inject: true, // Inject all files that are generated by webpack, e.g. bundle.js
			template: 'public/index.html',
		}),
		new CircularDependencyPlugin({
			exclude: /a\.js|node_modules/, // exclude node_modules
			failOnError: false, // show a warning when there is a circular dependency
		})
	],
	devtool: 'source-map'
})
